logger:
  level: info
  pretty: true

server:
  grpc:
    host: "0.0.0.0"
    port: 50051
    max_conn_age_seconds: 7200   # 2 часа
  http:
    host: "0.0.0.0"
    port: 8080
    read_timeout_seconds: 15
    write_timeout_seconds: 15
    read_header_timeout_seconds: 15

service_urls:
  profile_store: 'localhost:50051'
  har_profiler: 'localhost:50052'
  openapi_exporter: 'localhost:50054'